languageCode = "en-us"
title = "Signal to Noise"
baseURL = "https://signal-to-noise.xyz/"
theme = "hugo-zen"
name = "Michele Lacchia"
copyright = "Created by Michele Lacchia, built with Hugo"
disqusShortname = "signal-to-noise"
enableRobotsTXT = true

[markup.highlight]
noClasses = false

[taxonomies]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Michele Lacchia"
publisherName = "Signal to Noise"
logo = "/static/images/signal-to-noise.png"
github = "https://github.com/rubik/"
linkedin = "https://www.linkedin.com/in/michele-lacchia/"
obfuscated_email = """
document.write('<'+'a'+' '+'h'+'r'+'e'+'f'+'='+"'"+'m'+'a'+'i'+'&'+'#'+'1'+'0'+
'8'+';'+'t'+'o'+'&'+'#'+'5'+'8'+';'+'&'+'#'+'1'+'0'+'9'+';'+'i'+'c'+'h'+'&'+
'#'+'1'+'0'+'1'+';'+'&'+'#'+'1'+'0'+'8'+';'+'%'+'6'+'5'+'l'+'%'+'6'+'1'+'c'+
'c'+'%'+'6'+'8'+'i'+'a'+'%'+'&'+'#'+'5'+'2'+';'+'0'+'%'+'6'+'&'+'#'+'5'+'5'+
';'+'&'+'#'+'1'+'0'+'9'+';'+'&'+'#'+'9'+'7'+';'+'&'+'#'+'1'+'0'+'5'+';'+'l'+
'%'+'&'+'#'+'5'+'0'+';'+'E'+'%'+'6'+'3'+'o'+'m'+"'"+'>'+'E'+'m'+'a'+'i'+'&'+
'#'+'1'+'0'+'8'+';'+'<'+'/'+'a'+'>');"""
